version: '3.8'

services:
  shortliner-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SHORTLINER_BACKEND_URL=${SHORTLINER_BACKEND_URL:-http://localhost:8080}
      - ANALYTICS_BACKEND_URL=${ANALYTICS_BACKEND_URL:-http://localhost:8082}
    restart: unless-stopped
    image: shortliner-frontend
